# Generated by Django 2.2.6 on 2020-05-24 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0002_auto_20200524_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='novels.Team'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_users',
        ),
        migrations.AddField(
            model_name='team',
            name='team_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
