# Generated by Django 2.2.6 on 2020-05-26 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0003_auto_20200524_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='current_turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_turn_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novel',
            name='last_turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
