# Generated by Django 2.2.6 on 2020-06-03 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0004_auto_20200526_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='team_leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leading_novel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
