# Generated by Django 2.2.6 on 2020-06-04 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0005_novel_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='previous_turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_before_last', to=settings.AUTH_USER_MODEL),
        ),
    ]
