# Generated by Django 2.2.6 on 2020-06-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_publishednovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishednovel',
            name='team_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='novels.Team'),
            preserve_default=False,
        ),
    ]
