# Generated by Django 2.2.6 on 2020-06-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_publishednovel_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishednovel',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
