# Generated by Django 2.2.6 on 2020-06-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_publishednovel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishednovel',
            name='team_name',
        ),
    ]
