# Generated by Django 2.2.6 on 2020-06-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_remove_publishednovel_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishednovel',
            name='team_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
