# Generated by Django 2.2.6 on 2020-06-06 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0011_publishednovel_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishednovel',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
