# Generated by Django 2.2.6 on 2020-06-07 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0013_publishednovel_user_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishednovel',
            name='user_comments',
            field=models.ManyToManyField(related_name='commented', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishednovel',
            name='user_ratings',
            field=models.ManyToManyField(related_name='rated', to=settings.AUTH_USER_MODEL),
        ),
    ]
